run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - revive
    - unused
    - gosimple
    - gocritic
    - stylecheck

linters-settings:
  govet:
    enable:
      - unusedwrite
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 10
  exclude-use-default: false
  exclude-dirs:
    - dist
    - vendor
    - .gocache
    - .golangci-cache
  exclude-files:
    - ".*\\.pb\\.go"
