version: 2

builds:
  - id: rt
    main: ./cmd/rt
    binary: rt
    ldflags:
      - -s -w
      - -X github.com/frudas24/research-tree/cmd/rt/cmds.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

  - id: bridge
    main: ./cmd/rt-bridge
    binary: libretree
    buildmode: c-shared
    goos:
      - linux
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    overrides:
      - goos: windows
        goarch: amd64
        env:
          - CC=x86_64-w64-mingw32-gcc

archives:
  - id: default
    builds: [rt, bridge]
    formats: [tar.gz]
    allow_different_binary_count: true
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - docs/*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  prerelease: auto
